package co.edu.universidadean.interfaz;

import co.edu.universidadean.modelos.Categoria;
import co.edu.universidadean.modelos.Juego;
import co.edu.universidadean.modelos.Tienda;
import java.awt.Dimension;
import java.awt.FlowLayout;

/**
 *
 * @author Oscar Castrillón
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private Tienda tiendaJuegos;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        setLayout(new FlowLayout());
        tiendaJuegos = new Tienda("Tienda Vídeo Juegos");
        
        // Creación de juegos:
        Juego fifa = new Juego("Fifa 17", 7.67, 30, "fifa.png", Categoria.DEPORTES);
        
        tiendaJuegos.agregarJuego(fifa);
        
        JuegoJPanel panelFifa17 = new JuegoJPanel(this);
        panelFifa17.actualizarPanel(fifa);
        panelFifa17.setPreferredSize(new Dimension(450, 250));
        
        Juego nexomon = new Juego("Nexomon", 5.5, 25, "nexomon.jpg", Categoria.RPG);
        tiendaJuegos.agregarJuego(nexomon);
        JuegoJPanel panelNexomon = new JuegoJPanel(this);
        panelNexomon.actualizarPanel(nexomon);
        panelNexomon.setPreferredSize(new Dimension(450, 250));
        
        Juego pinball = new Juego("Pinball", 3.8, 10, "pinball.jpg", Categoria.ARCADE);
        tiendaJuegos.agregarJuego(pinball);
        JuegoJPanel panelPinball = new JuegoJPanel(this);
        panelPinball.actualizarPanel(pinball);
        panelPinball.setPreferredSize(new Dimension(450, 250));
        
        Juego modernCombat = new Juego("Modern Strike", 3.8, 20, "modern_strike.png", Categoria.FPS);
        tiendaJuegos.agregarJuego(modernCombat);
        JuegoJPanel panelModernCombat = new JuegoJPanel(this);
        panelModernCombat.setPreferredSize(new Dimension(450, 250));
        panelModernCombat.actualizarPanel(modernCombat);
        
        add(panelFifa17);
        add(panelNexomon);
        add(panelPinball);
        add(panelModernCombat);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jmbPrincipal = new javax.swing.JMenuBar();
        mnuArchivo = new javax.swing.JMenu();
        mniSalir = new javax.swing.JMenuItem();
        mnuOperaciones = new javax.swing.JMenu();
        mnuAyuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(930, 730));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/datos/fondo-tienda-juegos.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(897, 120));

        mnuArchivo.setText("Archivo");

        mniSalir.setLabel("Salir");
        mnuArchivo.add(mniSalir);

        jmbPrincipal.add(mnuArchivo);

        mnuOperaciones.setText("Operaciones");
        jmbPrincipal.add(mnuOperaciones);

        mnuAyuda.setLabel("Ayuda");
        jmbPrincipal.add(mnuAyuda);

        setJMenuBar(jmbPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 638, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jmbPrincipal;
    private javax.swing.JMenuItem mniSalir;
    private javax.swing.JMenu mnuArchivo;
    private javax.swing.JMenu mnuAyuda;
    private javax.swing.JMenu mnuOperaciones;
    // End of variables declaration//GEN-END:variables

    void venderJuego(Juego juego) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
